// Error keys
const LOGIN_FAILED = "";
const INVALID_USERNAME = "LOGIN.INVALID.USERNAME";
const INVALID_PASSWORD = "LOGIN.INVALID.PASSWORD";

// Success keys
const SIGN_UP_SUCCESS = "";
const LOGIN_SUCCESS = "";

export {
  LOGIN_FAILED,
  INVALID_USERNAME,
  INVALID_PASSWORD,
  SIGN_UP_SUCCESS,
  LOGIN_SUCCESS,
};
