// Error keys
const LOGIN_FAILED = "LOGIN.FAILED";
const INVALID_USERNAME = "LOGIN.INVALID.USERNAME";
const INVALID_PASSWORD = "LOGIN.INVALID.PASSWORD";
const SIGNUP_FAILED = "SIGNUP.FAILED";
const INVALID_CONFIRM_PASSWORD = "SIGNUP.INVALID.CONFIRM.PASSWORD";

// Success keys
const SIGNUP_SUCCESS = "";
const LOGIN_SUCCESS = "";

export {
  LOGIN_FAILED,
  INVALID_USERNAME,
  INVALID_PASSWORD,
  SIGNUP_FAILED,
  INVALID_CONFIRM_PASSWORD,
  SIGNUP_SUCCESS,
  LOGIN_SUCCESS,
};
